### PR TITLE
#5 | Added layout description to layout picker

### PR DESCRIPTION
**Pull request by jveer**
Also removed block description from this overview because this is not directly related to the view and can cause similar descriptions.

### CODE REVIEW

**Comment by PerplexDaniel** [comment]
Removing the block description itself makes sense if we indeed show the layout description, so agree on that.

The slide indicator however is now moved to the bottom right of the description, that's not where it was before. Especially with a long description this looks very odd (longer than in this screenshot):
cb

It is currently (in `master`) in that other position, aligned with the layout name. Preferably it stays there. 
cb1

**Comment by jveer** [comment]
Thanks for the quick feedback.

As slick places the dots themselves, the reason the dots are now moved to the bottom is that the size of the slick slider is expanded with the description element being inside the slider now as well.

I'm not familiar with the slick framework (backend developer myself), but also couldn't find anything about this online with some searches. If you have any idea on how to move the dots so they stay aligned with the title and also support different description lengths, I would love to know.

However, I think the dots at the bottom aren't that weird, as the description became part of the slider. You are now not only scrolling between different images, but the title and description are part of the slider as well. With the dots being placed at the bottom, this may be clearer for the end-user.

**Comment by PerplexDaniel** [comment]
So I looked at this a bit yesterday and I think I found a reasonable way to make it work. It pushed it to the branch [`feature/layout-description`](https://github.com/PerplexDigital/Perplex.ContentBlocks/tree/feature/layout-description). Your commit is also in there. You can have a look if you like and let me know your thoughts. I will probably release this soon in v1.4.0 once I have tested this a bit more.

Looks like this:
layout-description

**Comment by jveer** [comment]
That looks fine to me, thanks for helping! The only thing is that it 'feels' a bit like the text is not part of the slider.
But this might just be because we're just looking a bit too long at it 😉

**Comment by PerplexDaniel** [comment]
The name + description are now in another slider that is linked to the one with the preview images, so that might be why. I feel it's good enough now and then in some later release it can perhaps be streamlined a bit if more people are bothered by it. I'm already glad we can now show the layout descriptions so thanks again for the suggestion.

**Comment by jveer** [comment]
I totally agree with you! 👍

**Pull request merged**
