### PR TITLE
Add ability to translate text (#22)

### PR DESCRIPTION
**Pull request by AndersBrohus**
As i can see it should now be possible to translate the backoffice UI to other languages :)

### CODE REVIEW

**Comment by AndersBrohus** [comment]
Should fix issue #22  👍

**Comment by AndersBrohus** [comment]
Arh okay! :)

Looks great to me, so what's next step? :)

**Comment by PerplexDaniel** [comment]
I'll probably merge this + the Dutch translation very soon. Just released a new version today (`1.5.2`) that was already out as an RC so didn't want to rush this into that as well. 

This will be part of the next release, probably `1.6.0` as this is a new feature. Not sure yet when that one will be out, probably this week or next week. Of course I also have to work on other stuff here at Perplex so there is limited time :-)

**Comment by AndersBrohus** [comment]
Super :)

It was just if i needed to do something :)
Sounds great :)

**Pull request merged**
