### PR TITLE
Accessibility: Basic keyboard navigation

### PR DESCRIPTION
**Pull request by glombek**
Allows for basic keyboard navigation as per issue #4 .

### CODE REVIEW

**Comment by PerplexDaniel** [comment]
Hey @glombek thanks for the PR, I'll probably check and merge it next week. These look like some small changes that shouldn't break anything but I don't have time yet to check.

**Comment by glombek** [comment]
The most controvertial thing I did was remove `* { outline: none; }` - but I have tested this and can see no issues, looks like a part of a generic CSS reset.

**Comment by PerplexDaniel** [comment]
Had a very short look, but whenever I click a block header it will now get an outline. This also happens for other elements. These things should probably only show when focused with keyboard if possible? It looks rather bad when showing this all the time when just clicking it with a mouse:
header

Realistically I think the % of users that will actually use keyboard navigation is very small, so I am hesitant to include anything that degrades the user experience for the vast majority of users.

**Comment by PerplexDaniel** [comment]
Closed due to 4 weeks of inactivity.
Feel free to reopen with new input.

**Pull request closed without merging**
